### ISSUE TITLE
Rounded corners

### ISSUE THREAD

**Issue by aparsons** [toopay/bootstrap-markdown#163]
Bootstrap forms controls have rounded corners.

Here is what I did to make the editor look more like a bootstrap control.

```css
.md-editor {
  background-color: $input-bg;
  background-image: none;
  border: 1px solid $input-border;
  border-radius: $input-border-radius;
  @include box-shadow(inset 0 1px 1px rgba(0,0,0,.075));
  @include transition(border-color ease-in-out .15s, box-shadow ease-in-out .15s);

  .md-header {
    border-top-left-radius: $input-border-radius;
    border-top-right-radius: $input-border-radius;
  }

  textarea {
    padding: 6px 9px;
    background-color: #fff;
    border-bottom-left-radius: $input-border-radius;
    border-bottom-right-radius: $input-border-radius;
  }

  .md-preview {
    padding: 6px 9px;
    border-bottom-left-radius: $input-border-radius;
    border-bottom-right-radius: $input-border-radius;
  }
}
```
